layout_spectrum: 0.5430108
color:
  saturation: 0
  lightness: 0.3763441
  brandStrength: 0.5501792
  rhythmicContrast: 0.281362
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.5068257
name: Business Thoughts
